//
//  CardRotationSceneInteractor.swift
//  CardRotation
//
//  Created by Anish Kumar on 05/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardRotationSceneBusinessLogic
{
    var currentCardAngle: Float { get set }
    func rotateCard(request: CardRotationScene.Request, direction: CardRotationScene.RotationDirection)
}

protocol CardRotationSceneDataStore
{
    //var name: String { get set }
}

class CardRotationSceneInteractor: CardRotationSceneBusinessLogic, CardRotationSceneDataStore
{
    var presenter: CardRotationScenePresentationLogic?
    var worker: CardRotationSceneWorker?

    var currentCardAngle: Float = CRConstants.rotationStartAngle
    
    // MARK: Rotate Card
    
    /// Prepares the card rotation and calls the presenter to present it
    /// - Parameters:
    ///   - request: The request for rotating the card
    ///   - direction: Direction of rotation
    func rotateCard(request: CardRotationScene.Request, direction: CardRotationScene.RotationDirection)
    {
        worker = CardRotationSceneWorker()
        
        let response = worker!.getRotationValues(from: currentCardAngle, forRequest: request, towards: direction)
        presenter?.presentCardRotation(response: response)
        
        currentCardAngle = response.frontSide.toAngle.truncatingRemainder(dividingBy: 360)
    }
}
