//
//  CardRotationSceneModels.swift
//  CardRotation
//
//  Created by Anish Kumar on 05/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CardRotationScene
{
    // MARK: Use cases
    
    struct Request
    {
        var rotationAngle: Float
        var duration: CFTimeInterval
    }
    
    struct Response
    {
        var fromAngle: Float
        var toAngle: Float
        var rotationAngle: Float
        var fromValue: Float
        var toValue: Float
        var rotatedByValue: Float
        var duration: CFTimeInterval
    }
    
    struct ViewModel
    {
        var fromValue: Float
        var toValue: Float
        var rotatedByValue: Float
        var duration: CFTimeInterval
    }
    
    enum RotationDirection {
        case left
        case right
    }
}
