//
//  CardRotationSceneWorker.swift
//  CardRotation
//
//  Created by Anish Kumar on 05/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardRotationSceneWorker
{
    func getSavedCardAngle() -> Float
    {
        return 0.0
    }
    
    /// Gets the detailed rotation data for the specified rotation
    /// - Parameters:
    ///   - currentCardAngle: Current angle of the card
    ///   - request: The request for rotation
    ///   - direction: The direction of rotation
    func getRotationValues(from currentCardAngle: Float, forRequest request: CardRotationScene.Request, towards direction: CardRotationScene.RotationDirection) -> CardRotationScene.Response {
        let toAngle = getRotationAngle(fromAngle: currentCardAngle, rotatedBy: request.rotationAngle, direction: direction)
        
        let response = CardRotationScene.Response(frontFromAngle: currentCardAngle, frontToAngle: toAngle, rotationAngle: request.rotationAngle, duration: request.duration)
        return response
    }
    
    /// Gets the resultant angle of the rotation
    /// - Parameters:
    ///   - fromAngle: Angle from which the rotation starts
    ///   - rotatedBy: Angle by which the rotation is done
    ///   - direction: The direction of the rotation
    private func getRotationAngle(fromAngle: Float, rotatedBy: Float, direction: CardRotationScene.RotationDirection) -> Float {
        switch direction {
        case .left:
            return fromAngle - rotatedBy
        case .right:
            return fromAngle + rotatedBy
        }
    }
}
