//
//  CardRotationScenePresenter.swift
//  CardRotation
//
//  Created by Anish Kumar on 05/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardRotationScenePresentationLogic
{
    func presentCardRotation(response: CardRotationScene.Response)
}

class CardRotationScenePresenter: CardRotationScenePresentationLogic
{
    weak var viewController: CardRotationSceneDisplayLogic?
    
    // MARK: Present Card Rotation
    
    func presentCardRotation(response: CardRotationScene.Response)
    {
        let viewModel = CardRotationScene.ViewModel(fromValue: response.fromValue, toValue: response.toValue, rotatedByValue: response.rotatedByValue, duration: response.duration)
        viewController?.animateCardRotation(viewModel: viewModel)
    }
}
